CC = gcc
gcd_iter: gcd_iter.o main_iter.o
gcd_euclid: gcd_euclid.o main_euclid.o
gcd_recursive: gcd_recursive.o main_recursive.o
linked_list: linked_list.o main_linked_list.o
queue: queue.o main_queue.o 
doublylinked_list: doublylinked_list.o main_doublylinked_list.o
open_addressing: open_addressing.o main_open_addressing.o
double_hashing: double_hashing.o main_double_hashing.o
binarysearchtree: binarysearchtree.o main_binarysearchtree.o